name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Rename artifact
        run: mv target/*-jar-with-dependencies.jar ChatHub.jar
      
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ChatHub.jar
          asset_name: ChatHub-${{ github.ref_name }}.jar
          prerelease: true
          overwrite: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Generate changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}